### ISSUE TITLE
Consider BSD license

### ISSUE THREAD

**Issue by ghost** [astaranowicz/DCCT#1]
@astaranowicz As you already know, current licence does not allow proprietary development!
I believe giving the code in a voluntarily way is much appealing to many developers who might be interested in your implementation. Further, this licence would become a problem in case of proposing it to `OpenCV` or `ROS`.

What do you think?

**Comment by astaranowicz** [comment]
As this project was started as a research project, any researcher can use it without fear that some one will try to patent it.  With the GNU GPL3 license, this ensures that ANY changes by anyone must make it freely available.  

However, the GPL3 license does not block any proprietary development in terms of using this software.  If for example, a company has a new proprietary system that might need to be calibrated.  They might use this project for calibration but they must publish only changes to this project itself, not any proprietary software.   However, if they rewrote this project based on their own variables and optimization, then under GPL3 they would not need to publish those changes.  They would only have to include the copywrite and where they got the idea from in a contributors list.

Research projects should always benefit the wider community and any new ideas on this project should be published.  If ROS or OpenCV would like to integrate this project, they would have to rewrite it anyways, as they have done with many projects and algorithms in the past.
